import{a as f,S as g,i as h}from"./assets/vendor-D1eTGYtO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const y="https://pixabay.com/api/",v="45159640-00f670568c1d01c324bb6c884";async function L(t,o=1){try{return(await f.get(y,{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}catch(s){throw console.error("Error fetching images:",s),s}}function w(t){const o=new g(".gallery-list a",{captions:!0,captionsData:"alt",captionsDelay:250}),s=document.querySelector(".gallery-list");let a=t.hits.map(e=>`<div class="image-wrapper">
    <a href="${e.largeImageURL}">
    <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}"></img>
    </a>
    <div class="text-wrapper">
    <div class="text-item"><h5 class="text-header">Likes</h5><p class="text-paragraph">${e.likes}</p></div>
    <div class="text-item"><h5 class="text-header">Views</h5><p class="text-paragraph">${e.views}</p></div>
    <div class="text-item"><h5 class="text-header">Comments</h5><p class="text-paragraph">${e.comments}</p></div>
    <div class="text-item"><h5 class="text-header">Downloads</h5><p class="text-paragraph">${e.downloads}</p></div>
    </div>
    </div>`).join("");s.insertAdjacentHTML("beforeend",a),o.refresh()}function x(){const t=document.querySelector(".gallery-list");t.innerHTML=""}const p=document.querySelector(".form-gallery"),b=document.querySelector(".form-gallery-input"),l=document.querySelector(".loader"),d=document.querySelector(".load-more"),i=document.querySelector(".scroll-to-top");let n=1,u="";p.addEventListener("submit",S);d.addEventListener("click",q);i.addEventListener("click",P);async function S(t){t.preventDefault(),x(),l.classList.remove("hidden"),u=b.value.trim(),n=1,await m(),p.reset()}async function q(){n+=1,await m()}async function m(){try{const t=await L(u,n);if(l.classList.add("hidden"),t.total===0||u===""){h.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}w(t),t.hits.length===0||n*15>=t.totalHits?(d.classList.add("hidden"),h.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})):d.classList.remove("hidden"),T(),E()}catch(t){console.error(t),l.classList.add("hidden")}}function T(){const{height:t}=document.querySelector(".gallery-list").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}function E(){window.scrollY>1e3?i.classList.remove("hidden"):i.classList.add("hidden")}function P(){window.scrollTo({top:0,behavior:"auto"})}window.addEventListener("scroll",i);
//# sourceMappingURL=commonHelpers.js.map
